2020-03-06 10:07:43,192 - __main__ - INFO - >>>>> Starting development server at http://localhost:8888/api/ <<<<<
 * Serving Flask app "flaskr" (lazy loading)
 * Environment: production
   WARNING: This is a development server. Do not use it in a production deployment.
   Use a production WSGI server instead.
 * Debug mode: on
2020-03-06 10:07:43,200 - werkzeug - INFO -  * Running on http://localhost:8888/ (Press CTRL+C to quit)
2020-03-06 10:07:43,203 - werkzeug - INFO -  * Restarting with stat
2020-03-06 10:07:43,704 - __main__ - INFO - >>>>> Starting development server at http://localhost:8888/api/ <<<<<
2020-03-06 10:07:43,710 - werkzeug - WARNING -  * Debugger is active!
2020-03-06 10:07:43,711 - werkzeug - INFO -  * Debugger PIN: 288-488-263
2020-03-06 10:09:03,540 - __main__ - INFO - >>>>> Starting development server at http://localhost:8888/api/ <<<<<
 * Serving Flask app "flaskr" (lazy loading)
 * Environment: production
   WARNING: This is a development server. Do not use it in a production deployment.
   Use a production WSGI server instead.
 * Debug mode: on
2020-03-06 10:09:03,547 - werkzeug - INFO -  * Running on http://localhost:8888/ (Press CTRL+C to quit)
2020-03-06 10:09:03,550 - werkzeug - INFO -  * Restarting with stat
2020-03-06 10:09:04,054 - __main__ - INFO - >>>>> Starting development server at http://localhost:8888/api/ <<<<<
2020-03-06 10:09:04,060 - werkzeug - WARNING -  * Debugger is active!
2020-03-06 10:09:04,061 - werkzeug - INFO -  * Debugger PIN: 288-488-263
2020-03-06 10:10:55,966 - werkzeug - INFO -  * Detected change in '/home/prahtdooley/projects/rest_api_demo/rest_api_demo/settings.py', reloading
2020-03-06 10:10:55,999 - werkzeug - INFO -  * Restarting with stat
Traceback (most recent call last):
  File "/home/prahtdooley/projects/rest_api_demo/rest_api_demo/flaskr.py", line 58, in <module>
    main()
  File "/home/prahtdooley/projects/rest_api_demo/rest_api_demo/flaskr.py", line 52, in main
    initialize_app(app)
  File "/home/prahtdooley/projects/rest_api_demo/rest_api_demo/flaskr.py", line 34, in initialize_app
    configure_app(flask_app)
  File "/home/prahtdooley/projects/rest_api_demo/rest_api_demo/flaskr.py", line 24, in configure_app
    flask_app.config['SERVER_NAME'] = settings.FLASK_SERVER_NAME
AttributeError: 'module' object has no attribute 'FLASK_SERVER_NAME'
2020-03-06 10:11:31,423 - __main__ - INFO - >>>>> Starting development server at http://172.31.47.65:8888/api/ <<<<<
 * Serving Flask app "flaskr" (lazy loading)
 * Environment: production
   WARNING: This is a development server. Do not use it in a production deployment.
   Use a production WSGI server instead.
 * Debug mode: on
Traceback (most recent call last):
  File "rest_api_demo/flaskr.py", line 58, in <module>
    main()
  File "rest_api_demo/flaskr.py", line 54, in main
    app.run(debug=settings.FLASK_DEBUG)
  File "/home/prahtdooley/projects/rest_api_demo/venv/lib/python2.7/site-packages/flask/app.py", line 990, in run
    run_simple(host, port, self, **options)
  File "/home/prahtdooley/projects/rest_api_demo/venv/lib/python2.7/site-packages/werkzeug/serving.py", line 988, in run_simple
    s.bind(server_address)
  File "/usr/lib64/python2.7/socket.py", line 224, in meth
    return getattr(self._sock,name)(*args)
socket.error: [Errno 99] Cannot assign requested address
2020-03-06 10:11:59,049 - __main__ - INFO - >>>>> Starting development server at http://10.58.143.137:8888/api/ <<<<<
 * Serving Flask app "flaskr" (lazy loading)
 * Environment: production
   WARNING: This is a development server. Do not use it in a production deployment.
   Use a production WSGI server instead.
 * Debug mode: on
2020-03-06 10:11:59,056 - werkzeug - INFO -  * Running on http://10.58.143.137:8888/ (Press CTRL+C to quit)
2020-03-06 10:11:59,059 - werkzeug - INFO -  * Restarting with stat
2020-03-06 10:11:59,545 - __main__ - INFO - >>>>> Starting development server at http://10.58.143.137:8888/api/ <<<<<
2020-03-06 10:11:59,551 - werkzeug - WARNING -  * Debugger is active!
2020-03-06 10:11:59,552 - werkzeug - INFO -  * Debugger PIN: 288-488-263
2020-03-06 10:12:59,548 - werkzeug - INFO -  * Detected change in '/home/prahtdooley/projects/rest_api_demo/rest_api_demo/settings.py', reloading
2020-03-06 10:12:59,582 - werkzeug - INFO -  * Restarting with stat
Traceback (most recent call last):
  File "/home/prahtdooley/projects/rest_api_demo/rest_api_demo/flaskr.py", line 5, in <module>
    from rest_api_demo import settings
  File "/home/prahtdooley/projects/rest_api_demo/rest_api_demo/settings.py", line 8, in <module>
    FLASK_SERVER_NAME = os.environ['FLASK_SERVER_NAME'] # '10.58.143.137:8888'
  File "/home/prahtdooley/projects/rest_api_demo/venv/lib64/python2.7/UserDict.py", line 23, in __getitem__
    raise KeyError(key)
KeyError: 'FLASK_SERVER_NAME'
2020-03-06 10:13:28,476 - __main__ - INFO - >>>>> Starting development server at http://10.58.143.137:8888/api/ <<<<<
 * Serving Flask app "flaskr" (lazy loading)
 * Environment: production
   WARNING: This is a development server. Do not use it in a production deployment.
   Use a production WSGI server instead.
 * Debug mode: on
2020-03-06 10:13:28,483 - werkzeug - INFO -  * Running on http://10.58.143.137:8888/ (Press CTRL+C to quit)
2020-03-06 10:13:28,485 - werkzeug - INFO -  * Restarting with stat
2020-03-06 10:13:29,013 - __main__ - INFO - >>>>> Starting development server at http://10.58.143.137:8888/api/ <<<<<
2020-03-06 10:13:29,020 - werkzeug - WARNING -  * Debugger is active!
2020-03-06 10:13:29,020 - werkzeug - INFO -  * Debugger PIN: 288-488-263
2020-03-06 10:13:43,488 - werkzeug - INFO - 10.32.74.7 - - [06/Mar/2020 10:13:43] "GET /api/ HTTP/1.1" 200 -
2020-03-06 10:13:43,609 - werkzeug - INFO - 10.32.74.7 - - [06/Mar/2020 10:13:43] "GET /swaggerui/droid-sans.css HTTP/1.1" 200 -
2020-03-06 10:13:43,716 - werkzeug - INFO - 10.32.74.7 - - [06/Mar/2020 10:13:43] "GET /swaggerui/swagger-ui.css HTTP/1.1" 200 -
2020-03-06 10:13:43,717 - werkzeug - INFO - 10.32.74.7 - - [06/Mar/2020 10:13:43] "GET /swaggerui/swagger-ui-bundle.js HTTP/1.1" 200 -
2020-03-06 10:13:43,720 - werkzeug - INFO - 10.32.74.7 - - [06/Mar/2020 10:13:43] "GET /swaggerui/swagger-ui-standalone-preset.js HTTP/1.1" 200 -
2020-03-06 10:13:45,413 - werkzeug - INFO - 10.32.74.7 - - [06/Mar/2020 10:13:45] "GET /api/swagger.json HTTP/1.1" 200 -
2020-03-06 10:13:45,440 - werkzeug - INFO - 10.32.74.7 - - [06/Mar/2020 10:13:45] "GET /swaggerui/favicon-32x32.png HTTP/1.1" 200 -
2020-03-06 10:15:01,385 - werkzeug - INFO - 10.32.74.7 - - [06/Mar/2020 10:15:01] "GET /api/swagger.json HTTP/1.1" 200 -
{u'status': u'string', u'build_id': u'string', u'fqdn': u'string', u'ip': u'string', u'histories': [{u'timestamp': u'2020-03-06T15:14:17.373Z', u'server_id': u'string', u'id': 0, u'log': u'string'}], u'minion_id': u'string', u'os': u'string', u'id': 0}
2020-03-06 10:15:34,373 - werkzeug - INFO - 10.32.74.7 - - [06/Mar/2020 10:15:34] "POST /api/build/servers/ HTTP/1.1" 201 -
2020-03-06 10:19:18,006 - werkzeug - INFO - 10.32.74.7 - - [06/Mar/2020 10:19:18] "GET /api/build/servers/?page=1&bool=false&per_page=10 HTTP/1.1" 200 -
Update a server
Update Server
2020-03-06 10:19:45,959 - werkzeug - INFO - 10.32.74.7 - - [06/Mar/2020 10:19:45] "PUT /api/build/servers/1 HTTP/1.1" 204 -
2020-03-06 10:20:10,735 - werkzeug - INFO - 10.32.74.7 - - [06/Mar/2020 10:20:10] "GET /api/build/servers/?page=1&bool=false&per_page=10 HTTP/1.1" 200 -
./startserver.sh: line 6: python: command not found
./startserver.sh: line 6: python: command not found
Traceback (most recent call last):
  File "rest_api_demo/flaskr.py", line 4, in <module>
    from flask import Flask, Blueprint
ModuleNotFoundError: No module named 'flask'
2020-03-06 16:10:21,786 - __main__ - INFO - >>>>> Starting development server at http://ec2-3-18-92-220.us-east-2.compute.amazonaws.com:8888/api/ <<<<<
 * Serving Flask app "flaskr" (lazy loading)
 * Environment: production
   WARNING: This is a development server. Do not use it in a production deployment.
   Use a production WSGI server instead.
 * Debug mode: on
2020-03-06 16:10:21,794 - werkzeug - INFO -  * Running on http://ec2-3-18-92-220.us-east-2.compute.amazonaws.com:8888/ (Press CTRL+C to quit)
2020-03-06 16:10:21,794 - werkzeug - INFO -  * Restarting with stat
2020-03-06 16:10:22,164 - __main__ - INFO - >>>>> Starting development server at http://ec2-3-18-92-220.us-east-2.compute.amazonaws.com:8888/api/ <<<<<
2020-03-06 16:10:22,168 - werkzeug - WARNING -  * Debugger is active!
2020-03-06 16:10:22,168 - werkzeug - INFO -  * Debugger PIN: 299-073-171
2020-03-06 16:10:24,468 - werkzeug - INFO - 70.122.224.31 - - [06/Mar/2020 16:10:24] "GET /api/ HTTP/1.1" 200 -
2020-03-06 16:10:24,719 - werkzeug - INFO - 70.122.224.31 - - [06/Mar/2020 16:10:24] "GET /swaggerui/droid-sans.css HTTP/1.1" 200 -
2020-03-06 16:10:24,779 - werkzeug - INFO - 70.122.224.31 - - [06/Mar/2020 16:10:24] "GET /swaggerui/swagger-ui.css HTTP/1.1" 200 -
2020-03-06 16:10:24,781 - werkzeug - INFO - 70.122.224.31 - - [06/Mar/2020 16:10:24] "GET /swaggerui/swagger-ui-bundle.js HTTP/1.1" 200 -
2020-03-06 16:10:24,785 - werkzeug - INFO - 70.122.224.31 - - [06/Mar/2020 16:10:24] "GET /swaggerui/swagger-ui-standalone-preset.js HTTP/1.1" 200 -
2020-03-06 16:10:25,919 - werkzeug - INFO - 70.122.224.31 - - [06/Mar/2020 16:10:25] "GET /api/swagger.json HTTP/1.1" 200 -
2020-03-06 16:10:25,931 - werkzeug - INFO - 70.122.224.31 - - [06/Mar/2020 16:10:25] "GET /swaggerui/favicon-32x32.png HTTP/1.1" 200 -
Traceback (most recent call last):
  File "rest_api_demo/flaskr.py", line 6, in <module>
    from rest_api_demo.api.build.endpoints.servers import ns as server_namespace
  File "/home/prahtdooley/projects/rest_api_demo/rest_api_demo/api/build/endpoints/servers.py", line 4, in <module>
    from flask_restx import Resource
ImportError: No module named flask_restx
2020-03-06 11:40:23,126 - __main__ - INFO - >>>>> Starting development server at http://10.58.143.137:8888/api/ <<<<<
 * Serving Flask app "flaskr" (lazy loading)
 * Environment: production
   WARNING: This is a development server. Do not use it in a production deployment.
   Use a production WSGI server instead.
 * Debug mode: on
2020-03-06 11:40:23,133 - werkzeug - INFO -  * Running on http://10.58.143.137:8888/ (Press CTRL+C to quit)
2020-03-06 11:40:23,136 - werkzeug - INFO -  * Restarting with stat
2020-03-06 11:40:23,619 - __main__ - INFO - >>>>> Starting development server at http://10.58.143.137:8888/api/ <<<<<
2020-03-06 11:40:23,626 - werkzeug - WARNING -  * Debugger is active!
2020-03-06 11:40:23,627 - werkzeug - INFO -  * Debugger PIN: 288-488-263
2020-03-06 11:40:43,393 - werkzeug - INFO - 10.32.74.7 - - [06/Mar/2020 11:40:43] "GET /api/ HTTP/1.1" 200 -
2020-03-06 11:40:43,811 - werkzeug - INFO - 10.32.74.7 - - [06/Mar/2020 11:40:43] "GET /api/swagger.json HTTP/1.1" 200 -
2020-03-06 11:41:05,119 - werkzeug - INFO - 10.32.74.7 - - [06/Mar/2020 11:41:05] "GET /api/build/builds/?page=1&bool=false&per_page=10 HTTP/1.1" 200 -
2020-03-06 11:41:33,782 - werkzeug - INFO - 10.32.74.7 - - [06/Mar/2020 11:41:33] "GET /api/build/servers/?page=1&bool=true&per_page=10 HTTP/1.1" 200 -
2020-03-06 11:46:37,264 - __main__ - INFO - >>>>> Starting development server at http://10.58.143.137:8888/api/ <<<<<
 * Serving Flask app "flaskr" (lazy loading)
 * Environment: production
   WARNING: This is a development server. Do not use it in a production deployment.
   Use a production WSGI server instead.
 * Debug mode: on
2020-03-06 11:46:37,271 - werkzeug - INFO -  * Running on http://10.58.143.137:8888/ (Press CTRL+C to quit)
2020-03-06 11:46:37,274 - werkzeug - INFO -  * Restarting with stat
2020-03-06 11:46:37,789 - __main__ - INFO - >>>>> Starting development server at http://10.58.143.137:8888/api/ <<<<<
2020-03-06 11:46:37,795 - werkzeug - WARNING -  * Debugger is active!
2020-03-06 11:46:37,797 - werkzeug - INFO -  * Debugger PIN: 288-488-263
2020-03-06 11:46:45,202 - werkzeug - INFO - 10.32.74.7 - - [06/Mar/2020 11:46:45] "GET /api/ HTTP/1.1" 200 -
2020-03-06 11:46:45,705 - werkzeug - INFO - 10.32.74.7 - - [06/Mar/2020 11:46:45] "GET /api/swagger.json HTTP/1.1" 200 -
2020-03-06 11:46:45,774 - werkzeug - INFO - 10.32.74.7 - - [06/Mar/2020 11:46:45] "GET /swaggerui/favicon-32x32.png HTTP/1.1" 200 -
2020-03-06 11:47:03,819 - werkzeug - INFO - 10.32.74.7 - - [06/Mar/2020 11:47:03] "GET /api/build/servers/?page=1&bool=false&per_page=10 HTTP/1.1" 200 -
{u'status': u'string', u'build_id': u'string', u'fqdn': u'string', u'ip': u'string', u'histories': [{u'timestamp': u'2020-03-06T16:47:20.449Z', u'server_id': u'string', u'id': 0, u'log': u'string'}], u'minion_id': u'string', u'os': u'string', u'id': 0}
2020-03-06 11:47:25,576 - werkzeug - INFO - 10.32.74.7 - - [06/Mar/2020 11:47:25] "POST /api/build/servers/ HTTP/1.1" 201 -
Update a server
Update Server
2020-03-06 11:48:13,882 - werkzeug - INFO - 10.32.74.7 - - [06/Mar/2020 11:48:13] "PUT /api/build/servers/1 HTTP/1.1" 204 -
2020-03-06 11:48:21,888 - werkzeug - INFO - 10.32.74.7 - - [06/Mar/2020 11:48:21] "GET /api/build/servers/?page=1&bool=false&per_page=10 HTTP/1.1" 200 -
2020-03-06 11:50:54,862 - werkzeug - INFO - 10.32.74.7 - - [06/Mar/2020 11:50:54] "POST /api/qc/send_mail/ HTTP/1.1" 500 -
Traceback (most recent call last):
  File "/home/prahtdooley/projects/rest_api_demo/venv/lib/python2.7/site-packages/flask/app.py", line 2463, in __call__
    return self.wsgi_app(environ, start_response)
  File "/home/prahtdooley/projects/rest_api_demo/venv/lib/python2.7/site-packages/flask/app.py", line 2449, in wsgi_app
    response = self.handle_exception(e)
  File "/home/prahtdooley/projects/rest_api_demo/venv/lib/python2.7/site-packages/flask_restx/api.py", line 599, in error_router
    return original_handler(f)
  File "/home/prahtdooley/projects/rest_api_demo/venv/lib/python2.7/site-packages/flask/app.py", line 1866, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "/home/prahtdooley/projects/rest_api_demo/venv/lib/python2.7/site-packages/flask_restx/api.py", line 597, in error_router
    return self.handle_error(e)
  File "/home/prahtdooley/projects/rest_api_demo/venv/lib/python2.7/site-packages/flask/app.py", line 2446, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/prahtdooley/projects/rest_api_demo/venv/lib/python2.7/site-packages/flask/app.py", line 1951, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/prahtdooley/projects/rest_api_demo/venv/lib/python2.7/site-packages/flask_restx/api.py", line 599, in error_router
    return original_handler(f)
  File "/home/prahtdooley/projects/rest_api_demo/venv/lib/python2.7/site-packages/flask/app.py", line 1820, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/home/prahtdooley/projects/rest_api_demo/venv/lib/python2.7/site-packages/flask_restx/api.py", line 597, in error_router
    return self.handle_error(e)
  File "/home/prahtdooley/projects/rest_api_demo/venv/lib/python2.7/site-packages/flask/app.py", line 1949, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/prahtdooley/projects/rest_api_demo/venv/lib/python2.7/site-packages/flask/app.py", line 1935, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/home/prahtdooley/projects/rest_api_demo/venv/lib/python2.7/site-packages/flask_restx/api.py", line 339, in wrapper
    resp = resource(*args, **kwargs)
  File "/home/prahtdooley/projects/rest_api_demo/venv/lib/python2.7/site-packages/flask/views.py", line 89, in view
    return self.dispatch_request(*args, **kwargs)
  File "/home/prahtdooley/projects/rest_api_demo/venv/lib/python2.7/site-packages/flask_restx/resource.py", line 44, in dispatch_request
    resp = meth(*args, **kwargs)
  File "/home/prahtdooley/projects/rest_api_demo/rest_api_demo/api/qc/endpoints/send_mail.py", line 32, in post
    ret_data = send_mail(data)
  File "/home/prahtdooley/projects/rest_api_demo/rest_api_demo/api/qc/business.py", line 86, in send_mail
    smtp = smtplib.SMTP(server)
  File "/usr/lib64/python2.7/smtplib.py", line 255, in __init__
    (code, msg) = self.connect(host, port)
  File "/usr/lib64/python2.7/smtplib.py", line 315, in connect
    self.sock = self._get_socket(host, port, self.timeout)
  File "/usr/lib64/python2.7/smtplib.py", line 290, in _get_socket
    return socket.create_connection((host, port), timeout)
  File "/usr/lib64/python2.7/socket.py", line 553, in create_connection
    for res in getaddrinfo(host, port, 0, SOCK_STREAM):
gaierror: [Errno -2] Name or service not known
2020-03-06 11:51:26,582 - werkzeug - INFO - 10.32.74.7 - - [06/Mar/2020 11:51:26] "POST /api/qc/send_mail/ HTTP/1.1" 200 -
