2020-03-06 10:07:43,192 - __main__ - INFO - >>>>> Starting development server at http://localhost:8888/api/ <<<<<
 * Serving Flask app "flaskr" (lazy loading)
 * Environment: production
   WARNING: This is a development server. Do not use it in a production deployment.
   Use a production WSGI server instead.
 * Debug mode: on
2020-03-06 10:07:43,200 - werkzeug - INFO -  * Running on http://localhost:8888/ (Press CTRL+C to quit)
2020-03-06 10:07:43,203 - werkzeug - INFO -  * Restarting with stat
2020-03-06 10:07:43,704 - __main__ - INFO - >>>>> Starting development server at http://localhost:8888/api/ <<<<<
2020-03-06 10:07:43,710 - werkzeug - WARNING -  * Debugger is active!
2020-03-06 10:07:43,711 - werkzeug - INFO -  * Debugger PIN: 288-488-263
2020-03-06 10:09:03,540 - __main__ - INFO - >>>>> Starting development server at http://localhost:8888/api/ <<<<<
 * Serving Flask app "flaskr" (lazy loading)
 * Environment: production
   WARNING: This is a development server. Do not use it in a production deployment.
   Use a production WSGI server instead.
 * Debug mode: on
2020-03-06 10:09:03,547 - werkzeug - INFO -  * Running on http://localhost:8888/ (Press CTRL+C to quit)
2020-03-06 10:09:03,550 - werkzeug - INFO -  * Restarting with stat
2020-03-06 10:09:04,054 - __main__ - INFO - >>>>> Starting development server at http://localhost:8888/api/ <<<<<
2020-03-06 10:09:04,060 - werkzeug - WARNING -  * Debugger is active!
2020-03-06 10:09:04,061 - werkzeug - INFO -  * Debugger PIN: 288-488-263
2020-03-06 10:10:55,966 - werkzeug - INFO -  * Detected change in '/home/prahtdooley/projects/rest_api_demo/rest_api_demo/settings.py', reloading
2020-03-06 10:10:55,999 - werkzeug - INFO -  * Restarting with stat
Traceback (most recent call last):
  File "/home/prahtdooley/projects/rest_api_demo/rest_api_demo/flaskr.py", line 58, in <module>
    main()
  File "/home/prahtdooley/projects/rest_api_demo/rest_api_demo/flaskr.py", line 52, in main
    initialize_app(app)
  File "/home/prahtdooley/projects/rest_api_demo/rest_api_demo/flaskr.py", line 34, in initialize_app
    configure_app(flask_app)
  File "/home/prahtdooley/projects/rest_api_demo/rest_api_demo/flaskr.py", line 24, in configure_app
    flask_app.config['SERVER_NAME'] = settings.FLASK_SERVER_NAME
AttributeError: 'module' object has no attribute 'FLASK_SERVER_NAME'
2020-03-06 10:11:31,423 - __main__ - INFO - >>>>> Starting development server at http://172.31.47.65:8888/api/ <<<<<
 * Serving Flask app "flaskr" (lazy loading)
 * Environment: production
   WARNING: This is a development server. Do not use it in a production deployment.
   Use a production WSGI server instead.
 * Debug mode: on
Traceback (most recent call last):
  File "rest_api_demo/flaskr.py", line 58, in <module>
    main()
  File "rest_api_demo/flaskr.py", line 54, in main
    app.run(debug=settings.FLASK_DEBUG)
  File "/home/prahtdooley/projects/rest_api_demo/venv/lib/python2.7/site-packages/flask/app.py", line 990, in run
    run_simple(host, port, self, **options)
  File "/home/prahtdooley/projects/rest_api_demo/venv/lib/python2.7/site-packages/werkzeug/serving.py", line 988, in run_simple
    s.bind(server_address)
  File "/usr/lib64/python2.7/socket.py", line 224, in meth
    return getattr(self._sock,name)(*args)
socket.error: [Errno 99] Cannot assign requested address
2020-03-06 10:11:59,049 - __main__ - INFO - >>>>> Starting development server at http://10.58.143.137:8888/api/ <<<<<
 * Serving Flask app "flaskr" (lazy loading)
 * Environment: production
   WARNING: This is a development server. Do not use it in a production deployment.
   Use a production WSGI server instead.
 * Debug mode: on
2020-03-06 10:11:59,056 - werkzeug - INFO -  * Running on http://10.58.143.137:8888/ (Press CTRL+C to quit)
2020-03-06 10:11:59,059 - werkzeug - INFO -  * Restarting with stat
2020-03-06 10:11:59,545 - __main__ - INFO - >>>>> Starting development server at http://10.58.143.137:8888/api/ <<<<<
2020-03-06 10:11:59,551 - werkzeug - WARNING -  * Debugger is active!
2020-03-06 10:11:59,552 - werkzeug - INFO -  * Debugger PIN: 288-488-263
2020-03-06 10:12:59,548 - werkzeug - INFO -  * Detected change in '/home/prahtdooley/projects/rest_api_demo/rest_api_demo/settings.py', reloading
2020-03-06 10:12:59,582 - werkzeug - INFO -  * Restarting with stat
Traceback (most recent call last):
  File "/home/prahtdooley/projects/rest_api_demo/rest_api_demo/flaskr.py", line 5, in <module>
    from rest_api_demo import settings
  File "/home/prahtdooley/projects/rest_api_demo/rest_api_demo/settings.py", line 8, in <module>
    FLASK_SERVER_NAME = os.environ['FLASK_SERVER_NAME'] # '10.58.143.137:8888'
  File "/home/prahtdooley/projects/rest_api_demo/venv/lib64/python2.7/UserDict.py", line 23, in __getitem__
    raise KeyError(key)
KeyError: 'FLASK_SERVER_NAME'
2020-03-06 10:13:28,476 - __main__ - INFO - >>>>> Starting development server at http://10.58.143.137:8888/api/ <<<<<
 * Serving Flask app "flaskr" (lazy loading)
 * Environment: production
   WARNING: This is a development server. Do not use it in a production deployment.
   Use a production WSGI server instead.
 * Debug mode: on
2020-03-06 10:13:28,483 - werkzeug - INFO -  * Running on http://10.58.143.137:8888/ (Press CTRL+C to quit)
2020-03-06 10:13:28,485 - werkzeug - INFO -  * Restarting with stat
2020-03-06 10:13:29,013 - __main__ - INFO - >>>>> Starting development server at http://10.58.143.137:8888/api/ <<<<<
2020-03-06 10:13:29,020 - werkzeug - WARNING -  * Debugger is active!
2020-03-06 10:13:29,020 - werkzeug - INFO -  * Debugger PIN: 288-488-263
2020-03-06 10:13:43,488 - werkzeug - INFO - 10.32.74.7 - - [06/Mar/2020 10:13:43] "GET /api/ HTTP/1.1" 200 -
2020-03-06 10:13:43,609 - werkzeug - INFO - 10.32.74.7 - - [06/Mar/2020 10:13:43] "GET /swaggerui/droid-sans.css HTTP/1.1" 200 -
2020-03-06 10:13:43,716 - werkzeug - INFO - 10.32.74.7 - - [06/Mar/2020 10:13:43] "GET /swaggerui/swagger-ui.css HTTP/1.1" 200 -
2020-03-06 10:13:43,717 - werkzeug - INFO - 10.32.74.7 - - [06/Mar/2020 10:13:43] "GET /swaggerui/swagger-ui-bundle.js HTTP/1.1" 200 -
2020-03-06 10:13:43,720 - werkzeug - INFO - 10.32.74.7 - - [06/Mar/2020 10:13:43] "GET /swaggerui/swagger-ui-standalone-preset.js HTTP/1.1" 200 -
2020-03-06 10:13:45,413 - werkzeug - INFO - 10.32.74.7 - - [06/Mar/2020 10:13:45] "GET /api/swagger.json HTTP/1.1" 200 -
2020-03-06 10:13:45,440 - werkzeug - INFO - 10.32.74.7 - - [06/Mar/2020 10:13:45] "GET /swaggerui/favicon-32x32.png HTTP/1.1" 200 -
2020-03-06 10:15:01,385 - werkzeug - INFO - 10.32.74.7 - - [06/Mar/2020 10:15:01] "GET /api/swagger.json HTTP/1.1" 200 -
{u'status': u'string', u'build_id': u'string', u'fqdn': u'string', u'ip': u'string', u'histories': [{u'timestamp': u'2020-03-06T15:14:17.373Z', u'server_id': u'string', u'id': 0, u'log': u'string'}], u'minion_id': u'string', u'os': u'string', u'id': 0}
2020-03-06 10:15:34,373 - werkzeug - INFO - 10.32.74.7 - - [06/Mar/2020 10:15:34] "POST /api/build/servers/ HTTP/1.1" 201 -
2020-03-06 10:19:18,006 - werkzeug - INFO - 10.32.74.7 - - [06/Mar/2020 10:19:18] "GET /api/build/servers/?page=1&bool=false&per_page=10 HTTP/1.1" 200 -
Update a server
Update Server
2020-03-06 10:19:45,959 - werkzeug - INFO - 10.32.74.7 - - [06/Mar/2020 10:19:45] "PUT /api/build/servers/1 HTTP/1.1" 204 -
2020-03-06 10:20:10,735 - werkzeug - INFO - 10.32.74.7 - - [06/Mar/2020 10:20:10] "GET /api/build/servers/?page=1&bool=false&per_page=10 HTTP/1.1" 200 -
./startserver.sh: line 6: python: command not found
./startserver.sh: line 6: python: command not found
Traceback (most recent call last):
  File "rest_api_demo/flaskr.py", line 4, in <module>
    from flask import Flask, Blueprint
ModuleNotFoundError: No module named 'flask'
2020-03-06 16:10:21,786 - __main__ - INFO - >>>>> Starting development server at http://ec2-3-18-92-220.us-east-2.compute.amazonaws.com:8888/api/ <<<<<
 * Serving Flask app "flaskr" (lazy loading)
 * Environment: production
   WARNING: This is a development server. Do not use it in a production deployment.
   Use a production WSGI server instead.
 * Debug mode: on
2020-03-06 16:10:21,794 - werkzeug - INFO -  * Running on http://ec2-3-18-92-220.us-east-2.compute.amazonaws.com:8888/ (Press CTRL+C to quit)
2020-03-06 16:10:21,794 - werkzeug - INFO -  * Restarting with stat
2020-03-06 16:10:22,164 - __main__ - INFO - >>>>> Starting development server at http://ec2-3-18-92-220.us-east-2.compute.amazonaws.com:8888/api/ <<<<<
2020-03-06 16:10:22,168 - werkzeug - WARNING -  * Debugger is active!
2020-03-06 16:10:22,168 - werkzeug - INFO -  * Debugger PIN: 299-073-171
2020-03-06 16:10:24,468 - werkzeug - INFO - 70.122.224.31 - - [06/Mar/2020 16:10:24] "GET /api/ HTTP/1.1" 200 -
2020-03-06 16:10:24,719 - werkzeug - INFO - 70.122.224.31 - - [06/Mar/2020 16:10:24] "GET /swaggerui/droid-sans.css HTTP/1.1" 200 -
2020-03-06 16:10:24,779 - werkzeug - INFO - 70.122.224.31 - - [06/Mar/2020 16:10:24] "GET /swaggerui/swagger-ui.css HTTP/1.1" 200 -
2020-03-06 16:10:24,781 - werkzeug - INFO - 70.122.224.31 - - [06/Mar/2020 16:10:24] "GET /swaggerui/swagger-ui-bundle.js HTTP/1.1" 200 -
2020-03-06 16:10:24,785 - werkzeug - INFO - 70.122.224.31 - - [06/Mar/2020 16:10:24] "GET /swaggerui/swagger-ui-standalone-preset.js HTTP/1.1" 200 -
2020-03-06 16:10:25,919 - werkzeug - INFO - 70.122.224.31 - - [06/Mar/2020 16:10:25] "GET /api/swagger.json HTTP/1.1" 200 -
2020-03-06 16:10:25,931 - werkzeug - INFO - 70.122.224.31 - - [06/Mar/2020 16:10:25] "GET /swaggerui/favicon-32x32.png HTTP/1.1" 200 -
Traceback (most recent call last):
  File "rest_api_demo/flaskr.py", line 6, in <module>
    from rest_api_demo.api.build.endpoints.servers import ns as server_namespace
  File "/home/prahtdooley/projects/rest_api_demo/rest_api_demo/api/build/endpoints/servers.py", line 4, in <module>
    from flask_restx import Resource
ImportError: No module named flask_restx
2020-03-06 11:40:23,126 - __main__ - INFO - >>>>> Starting development server at http://10.58.143.137:8888/api/ <<<<<
 * Serving Flask app "flaskr" (lazy loading)
 * Environment: production
   WARNING: This is a development server. Do not use it in a production deployment.
   Use a production WSGI server instead.
 * Debug mode: on
2020-03-06 11:40:23,133 - werkzeug - INFO -  * Running on http://10.58.143.137:8888/ (Press CTRL+C to quit)
2020-03-06 11:40:23,136 - werkzeug - INFO -  * Restarting with stat
2020-03-06 11:40:23,619 - __main__ - INFO - >>>>> Starting development server at http://10.58.143.137:8888/api/ <<<<<
2020-03-06 11:40:23,626 - werkzeug - WARNING -  * Debugger is active!
2020-03-06 11:40:23,627 - werkzeug - INFO -  * Debugger PIN: 288-488-263
2020-03-06 11:40:43,393 - werkzeug - INFO - 10.32.74.7 - - [06/Mar/2020 11:40:43] "GET /api/ HTTP/1.1" 200 -
2020-03-06 11:40:43,811 - werkzeug - INFO - 10.32.74.7 - - [06/Mar/2020 11:40:43] "GET /api/swagger.json HTTP/1.1" 200 -
2020-03-06 11:41:05,119 - werkzeug - INFO - 10.32.74.7 - - [06/Mar/2020 11:41:05] "GET /api/build/builds/?page=1&bool=false&per_page=10 HTTP/1.1" 200 -
2020-03-06 11:41:33,782 - werkzeug - INFO - 10.32.74.7 - - [06/Mar/2020 11:41:33] "GET /api/build/servers/?page=1&bool=true&per_page=10 HTTP/1.1" 200 -
2020-03-06 11:46:37,264 - __main__ - INFO - >>>>> Starting development server at http://10.58.143.137:8888/api/ <<<<<
 * Serving Flask app "flaskr" (lazy loading)
 * Environment: production
   WARNING: This is a development server. Do not use it in a production deployment.
   Use a production WSGI server instead.
 * Debug mode: on
2020-03-06 11:46:37,271 - werkzeug - INFO -  * Running on http://10.58.143.137:8888/ (Press CTRL+C to quit)
2020-03-06 11:46:37,274 - werkzeug - INFO -  * Restarting with stat
2020-03-06 11:46:37,789 - __main__ - INFO - >>>>> Starting development server at http://10.58.143.137:8888/api/ <<<<<
2020-03-06 11:46:37,795 - werkzeug - WARNING -  * Debugger is active!
2020-03-06 11:46:37,797 - werkzeug - INFO -  * Debugger PIN: 288-488-263
2020-03-06 11:46:45,202 - werkzeug - INFO - 10.32.74.7 - - [06/Mar/2020 11:46:45] "GET /api/ HTTP/1.1" 200 -
2020-03-06 11:46:45,705 - werkzeug - INFO - 10.32.74.7 - - [06/Mar/2020 11:46:45] "GET /api/swagger.json HTTP/1.1" 200 -
2020-03-06 11:46:45,774 - werkzeug - INFO - 10.32.74.7 - - [06/Mar/2020 11:46:45] "GET /swaggerui/favicon-32x32.png HTTP/1.1" 200 -
2020-03-06 11:47:03,819 - werkzeug - INFO - 10.32.74.7 - - [06/Mar/2020 11:47:03] "GET /api/build/servers/?page=1&bool=false&per_page=10 HTTP/1.1" 200 -
{u'status': u'string', u'build_id': u'string', u'fqdn': u'string', u'ip': u'string', u'histories': [{u'timestamp': u'2020-03-06T16:47:20.449Z', u'server_id': u'string', u'id': 0, u'log': u'string'}], u'minion_id': u'string', u'os': u'string', u'id': 0}
2020-03-06 11:47:25,576 - werkzeug - INFO - 10.32.74.7 - - [06/Mar/2020 11:47:25] "POST /api/build/servers/ HTTP/1.1" 201 -
Update a server
Update Server
2020-03-06 11:48:13,882 - werkzeug - INFO - 10.32.74.7 - - [06/Mar/2020 11:48:13] "PUT /api/build/servers/1 HTTP/1.1" 204 -
2020-03-06 11:48:21,888 - werkzeug - INFO - 10.32.74.7 - - [06/Mar/2020 11:48:21] "GET /api/build/servers/?page=1&bool=false&per_page=10 HTTP/1.1" 200 -
2020-03-06 11:50:54,862 - werkzeug - INFO - 10.32.74.7 - - [06/Mar/2020 11:50:54] "POST /api/qc/send_mail/ HTTP/1.1" 500 -
Traceback (most recent call last):
  File "/home/prahtdooley/projects/rest_api_demo/venv/lib/python2.7/site-packages/flask/app.py", line 2463, in __call__
    return self.wsgi_app(environ, start_response)
  File "/home/prahtdooley/projects/rest_api_demo/venv/lib/python2.7/site-packages/flask/app.py", line 2449, in wsgi_app
    response = self.handle_exception(e)
  File "/home/prahtdooley/projects/rest_api_demo/venv/lib/python2.7/site-packages/flask_restx/api.py", line 599, in error_router
    return original_handler(f)
  File "/home/prahtdooley/projects/rest_api_demo/venv/lib/python2.7/site-packages/flask/app.py", line 1866, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "/home/prahtdooley/projects/rest_api_demo/venv/lib/python2.7/site-packages/flask_restx/api.py", line 597, in error_router
    return self.handle_error(e)
  File "/home/prahtdooley/projects/rest_api_demo/venv/lib/python2.7/site-packages/flask/app.py", line 2446, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/prahtdooley/projects/rest_api_demo/venv/lib/python2.7/site-packages/flask/app.py", line 1951, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/prahtdooley/projects/rest_api_demo/venv/lib/python2.7/site-packages/flask_restx/api.py", line 599, in error_router
    return original_handler(f)
  File "/home/prahtdooley/projects/rest_api_demo/venv/lib/python2.7/site-packages/flask/app.py", line 1820, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/home/prahtdooley/projects/rest_api_demo/venv/lib/python2.7/site-packages/flask_restx/api.py", line 597, in error_router
    return self.handle_error(e)
  File "/home/prahtdooley/projects/rest_api_demo/venv/lib/python2.7/site-packages/flask/app.py", line 1949, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/prahtdooley/projects/rest_api_demo/venv/lib/python2.7/site-packages/flask/app.py", line 1935, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/home/prahtdooley/projects/rest_api_demo/venv/lib/python2.7/site-packages/flask_restx/api.py", line 339, in wrapper
    resp = resource(*args, **kwargs)
  File "/home/prahtdooley/projects/rest_api_demo/venv/lib/python2.7/site-packages/flask/views.py", line 89, in view
    return self.dispatch_request(*args, **kwargs)
  File "/home/prahtdooley/projects/rest_api_demo/venv/lib/python2.7/site-packages/flask_restx/resource.py", line 44, in dispatch_request
    resp = meth(*args, **kwargs)
  File "/home/prahtdooley/projects/rest_api_demo/rest_api_demo/api/qc/endpoints/send_mail.py", line 32, in post
    ret_data = send_mail(data)
  File "/home/prahtdooley/projects/rest_api_demo/rest_api_demo/api/qc/business.py", line 86, in send_mail
    smtp = smtplib.SMTP(server)
  File "/usr/lib64/python2.7/smtplib.py", line 255, in __init__
    (code, msg) = self.connect(host, port)
  File "/usr/lib64/python2.7/smtplib.py", line 315, in connect
    self.sock = self._get_socket(host, port, self.timeout)
  File "/usr/lib64/python2.7/smtplib.py", line 290, in _get_socket
    return socket.create_connection((host, port), timeout)
  File "/usr/lib64/python2.7/socket.py", line 553, in create_connection
    for res in getaddrinfo(host, port, 0, SOCK_STREAM):
gaierror: [Errno -2] Name or service not known
2020-03-06 11:51:26,582 - werkzeug - INFO - 10.32.74.7 - - [06/Mar/2020 11:51:26] "POST /api/qc/send_mail/ HTTP/1.1" 200 -
2020-03-06 12:32:32,233 - __main__ - INFO - >>>>> Starting development server at http://10.58.143.137:8888/api/ <<<<<
 * Serving Flask app "flaskr" (lazy loading)
 * Environment: production
   WARNING: This is a development server. Do not use it in a production deployment.
   Use a production WSGI server instead.
 * Debug mode: on
2020-03-06 12:32:32,241 - werkzeug - INFO -  * Running on http://10.58.143.137:8888/ (Press CTRL+C to quit)
2020-03-06 12:32:32,243 - werkzeug - INFO -  * Restarting with stat
2020-03-06 12:32:32,733 - __main__ - INFO - >>>>> Starting development server at http://10.58.143.137:8888/api/ <<<<<
2020-03-06 12:32:32,739 - werkzeug - WARNING -  * Debugger is active!
2020-03-06 12:32:32,740 - werkzeug - INFO -  * Debugger PIN: 288-488-263
2020-03-06 12:32:35,928 - werkzeug - INFO - 10.32.74.7 - - [06/Mar/2020 12:32:35] "GET /api/ HTTP/1.1" 200 -
2020-03-06 12:32:36,244 - werkzeug - INFO - 10.32.74.7 - - [06/Mar/2020 12:32:36] "GET /api/swagger.json HTTP/1.1" 200 -
2020-03-06 12:32:36,314 - werkzeug - INFO - 10.32.74.7 - - [06/Mar/2020 12:32:36] "GET /swaggerui/favicon-32x32.png HTTP/1.1" 200 -
2020-03-06 12:33:19,644 - werkzeug - INFO - 10.32.74.7 - - [06/Mar/2020 12:33:19] "GET /api/build/servers/?page=1&bool=false&per_page=10 HTTP/1.1" 200 -
2020-03-06 12:40:16,116 - werkzeug - INFO - 10.32.74.7 - - [06/Mar/2020 12:40:16] "GET /api/build/servers/?page=1&bool=false&per_page=10%22%20-H%20%22accept:%20application/json HTTP/1.1" 400 -
2020-03-06 12:40:50,779 - werkzeug - INFO - 10.32.74.7 - - [06/Mar/2020 12:40:50] "GET /api/build/servers/?page=1&bool=false&per_page=10 HTTP/1.1" 200 -
{u'status': u'init', u'build_id': u'DMND1234', u'fqdn': u'minion_1.kpmg.com', u'ip': u'123.123.123.123', u'histories': [{u'timestamp': u'2020-03-06T17:41:02.436Z', u'server_id': u'string', u'log': u'init'}], u'minion_id': u'minion_1', u'os': u'linux', u'id': 0}
2020-03-06 12:42:01,938 - werkzeug - INFO - 10.32.74.7 - - [06/Mar/2020 12:42:01] "POST /api/build/servers/ HTTP/1.1" 201 -
None
2020-03-06 12:46:22,021 - werkzeug - INFO - 10.32.74.7 - - [06/Mar/2020 12:46:22] "POST /api/build/servers/ HTTP/1.1" 500 -
Traceback (most recent call last):
  File "/home/prahtdooley/projects/rest_api_demo/venv/lib/python2.7/site-packages/flask/app.py", line 2463, in __call__
    return self.wsgi_app(environ, start_response)
  File "/home/prahtdooley/projects/rest_api_demo/venv/lib/python2.7/site-packages/flask/app.py", line 2449, in wsgi_app
    response = self.handle_exception(e)
  File "/home/prahtdooley/projects/rest_api_demo/venv/lib/python2.7/site-packages/flask_restx/api.py", line 599, in error_router
    return original_handler(f)
  File "/home/prahtdooley/projects/rest_api_demo/venv/lib/python2.7/site-packages/flask/app.py", line 1866, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "/home/prahtdooley/projects/rest_api_demo/venv/lib/python2.7/site-packages/flask_restx/api.py", line 597, in error_router
    return self.handle_error(e)
  File "/home/prahtdooley/projects/rest_api_demo/venv/lib/python2.7/site-packages/flask/app.py", line 2446, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/prahtdooley/projects/rest_api_demo/venv/lib/python2.7/site-packages/flask/app.py", line 1951, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/prahtdooley/projects/rest_api_demo/venv/lib/python2.7/site-packages/flask_restx/api.py", line 599, in error_router
    return original_handler(f)
  File "/home/prahtdooley/projects/rest_api_demo/venv/lib/python2.7/site-packages/flask/app.py", line 1820, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/home/prahtdooley/projects/rest_api_demo/venv/lib/python2.7/site-packages/flask_restx/api.py", line 597, in error_router
    return self.handle_error(e)
  File "/home/prahtdooley/projects/rest_api_demo/venv/lib/python2.7/site-packages/flask/app.py", line 1949, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/prahtdooley/projects/rest_api_demo/venv/lib/python2.7/site-packages/flask/app.py", line 1935, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/home/prahtdooley/projects/rest_api_demo/venv/lib/python2.7/site-packages/flask_restx/api.py", line 339, in wrapper
    resp = resource(*args, **kwargs)
  File "/home/prahtdooley/projects/rest_api_demo/venv/lib/python2.7/site-packages/flask/views.py", line 89, in view
    return self.dispatch_request(*args, **kwargs)
  File "/home/prahtdooley/projects/rest_api_demo/venv/lib/python2.7/site-packages/flask_restx/resource.py", line 44, in dispatch_request
    resp = meth(*args, **kwargs)
  File "/home/prahtdooley/projects/rest_api_demo/rest_api_demo/api/build/endpoints/servers.py", line 40, in post
    create_server(request.json)
  File "/home/prahtdooley/projects/rest_api_demo/rest_api_demo/api/build/business.py", line 12, in create_server
    minion_id = data.get('minion_id')
AttributeError: 'NoneType' object has no attribute 'get'
{u'status': u'init', u'build_id': u'DMND1234', u'fqdn': u'minion_1.kpmg.com', u'ip': u'123.123.123.123', u'histories': [{u'timestamp': u'2020-03-06T17:41:02.436Z', u'server_id': u'string', u'log': u'init'}], u'minion_id': u'minion_1', u'os': u'linux', u'id': 0}
2020-03-06 12:48:45,980 - werkzeug - INFO - 10.32.74.7 - - [06/Mar/2020 12:48:45] "POST /api/build/servers/ HTTP/1.1" 201 -
2020-03-06 12:48:53,041 - werkzeug - INFO - 10.32.74.7 - - [06/Mar/2020 12:48:53] "GET /api/build/servers/?page=1&bool=false&per_page=10 HTTP/1.1" 200 -
{u'status': u'init', u'build_id': u'DMND1234', u'fqdn': u'minion_1.kpmg.com', u'ip': u'123.123.123.123', u'histories': [{u'timestamp': u'2020-03-06T17:41:02.436Z', u'server_id': u'string', u'log': u'init'}], u'minion_id': u'minion_1', u'os': u'linux'}
2020-03-06 12:49:05,830 - werkzeug - INFO - 10.32.74.7 - - [06/Mar/2020 12:49:05] "POST /api/build/servers/ HTTP/1.1" 201 -
2020-03-06 12:49:12,462 - werkzeug - INFO - 10.32.74.7 - - [06/Mar/2020 12:49:12] "GET /api/build/servers/?page=1&bool=false&per_page=10 HTTP/1.1" 200 -
{u'timestamp': u'2020-03-06T17:50:18.103Z', u'server_id': u'0', u'id': 0, u'log': u'string'}
2020-03-06 12:50:33,600 - werkzeug - INFO - 10.32.74.7 - - [06/Mar/2020 12:50:33] "POST /api/build/serverhistories/ HTTP/1.1" 201 -
{u'timestamp': u'2020-03-06T17:50:18.103Z', u'server_id': u'0', u'id': 1, u'log': u'NEW LOG MESSAGE'}
2020-03-06 12:51:21,255 - werkzeug - INFO - 10.32.74.7 - - [06/Mar/2020 12:51:21] "POST /api/build/serverhistories/ HTTP/1.1" 500 -
Traceback (most recent call last):
  File "/home/prahtdooley/projects/rest_api_demo/venv/lib/python2.7/site-packages/flask/app.py", line 2463, in __call__
    return self.wsgi_app(environ, start_response)
  File "/home/prahtdooley/projects/rest_api_demo/venv/lib/python2.7/site-packages/flask/app.py", line 2449, in wsgi_app
    response = self.handle_exception(e)
  File "/home/prahtdooley/projects/rest_api_demo/venv/lib/python2.7/site-packages/flask_restx/api.py", line 599, in error_router
    return original_handler(f)
  File "/home/prahtdooley/projects/rest_api_demo/venv/lib/python2.7/site-packages/flask/app.py", line 1866, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "/home/prahtdooley/projects/rest_api_demo/venv/lib/python2.7/site-packages/flask_restx/api.py", line 597, in error_router
    return self.handle_error(e)
  File "/home/prahtdooley/projects/rest_api_demo/venv/lib/python2.7/site-packages/flask/app.py", line 2446, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/prahtdooley/projects/rest_api_demo/venv/lib/python2.7/site-packages/flask/app.py", line 1951, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/prahtdooley/projects/rest_api_demo/venv/lib/python2.7/site-packages/flask_restx/api.py", line 599, in error_router
    return original_handler(f)
  File "/home/prahtdooley/projects/rest_api_demo/venv/lib/python2.7/site-packages/flask/app.py", line 1820, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/home/prahtdooley/projects/rest_api_demo/venv/lib/python2.7/site-packages/flask_restx/api.py", line 597, in error_router
    return self.handle_error(e)
  File "/home/prahtdooley/projects/rest_api_demo/venv/lib/python2.7/site-packages/flask/app.py", line 1949, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/prahtdooley/projects/rest_api_demo/venv/lib/python2.7/site-packages/flask/app.py", line 1935, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/home/prahtdooley/projects/rest_api_demo/venv/lib/python2.7/site-packages/flask_restx/api.py", line 339, in wrapper
    resp = resource(*args, **kwargs)
  File "/home/prahtdooley/projects/rest_api_demo/venv/lib/python2.7/site-packages/flask/views.py", line 89, in view
    return self.dispatch_request(*args, **kwargs)
  File "/home/prahtdooley/projects/rest_api_demo/venv/lib/python2.7/site-packages/flask_restx/resource.py", line 44, in dispatch_request
    resp = meth(*args, **kwargs)
  File "/home/prahtdooley/projects/rest_api_demo/rest_api_demo/api/build/endpoints/server_histories.py", line 40, in post
    create_server_history(request.json)
  File "/home/prahtdooley/projects/rest_api_demo/rest_api_demo/api/build/business.py", line 119, in create_server_history
    db.session.commit()
  File "/home/prahtdooley/projects/rest_api_demo/venv/lib/python2.7/site-packages/sqlalchemy/orm/scoping.py", line 162, in do
    return getattr(self.registry(), name)(*args, **kwargs)
  File "/home/prahtdooley/projects/rest_api_demo/venv/lib/python2.7/site-packages/sqlalchemy/orm/session.py", line 1027, in commit
    self.transaction.commit()
  File "/home/prahtdooley/projects/rest_api_demo/venv/lib/python2.7/site-packages/sqlalchemy/orm/session.py", line 494, in commit
    self._prepare_impl()
  File "/home/prahtdooley/projects/rest_api_demo/venv/lib/python2.7/site-packages/sqlalchemy/orm/session.py", line 473, in _prepare_impl
    self.session.flush()
  File "/home/prahtdooley/projects/rest_api_demo/venv/lib/python2.7/site-packages/sqlalchemy/orm/session.py", line 2470, in flush
    self._flush(objects)
  File "/home/prahtdooley/projects/rest_api_demo/venv/lib/python2.7/site-packages/sqlalchemy/orm/session.py", line 2608, in _flush
    transaction.rollback(_capture_exception=True)
  File "/home/prahtdooley/projects/rest_api_demo/venv/lib/python2.7/site-packages/sqlalchemy/util/langhelpers.py", line 68, in __exit__
    compat.reraise(exc_type, exc_value, exc_tb)
  File "/home/prahtdooley/projects/rest_api_demo/venv/lib/python2.7/site-packages/sqlalchemy/orm/session.py", line 2568, in _flush
    flush_context.execute()
  File "/home/prahtdooley/projects/rest_api_demo/venv/lib/python2.7/site-packages/sqlalchemy/orm/unitofwork.py", line 422, in execute
    rec.execute(self)
  File "/home/prahtdooley/projects/rest_api_demo/venv/lib/python2.7/site-packages/sqlalchemy/orm/unitofwork.py", line 589, in execute
    uow,
  File "/home/prahtdooley/projects/rest_api_demo/venv/lib/python2.7/site-packages/sqlalchemy/orm/persistence.py", line 245, in save_obj
    insert,
  File "/home/prahtdooley/projects/rest_api_demo/venv/lib/python2.7/site-packages/sqlalchemy/orm/persistence.py", line 1084, in _emit_insert_statements
    c = cached_connections[connection].execute(statement, multiparams)
  File "/home/prahtdooley/projects/rest_api_demo/venv/lib/python2.7/site-packages/sqlalchemy/engine/base.py", line 988, in execute
    return meth(self, multiparams, params)
  File "/home/prahtdooley/projects/rest_api_demo/venv/lib/python2.7/site-packages/sqlalchemy/sql/elements.py", line 287, in _execute_on_connection
    return connection._execute_clauseelement(self, multiparams, params)
  File "/home/prahtdooley/projects/rest_api_demo/venv/lib/python2.7/site-packages/sqlalchemy/engine/base.py", line 1107, in _execute_clauseelement
    distilled_params,
  File "/home/prahtdooley/projects/rest_api_demo/venv/lib/python2.7/site-packages/sqlalchemy/engine/base.py", line 1253, in _execute_context
    e, statement, parameters, cursor, context
  File "/home/prahtdooley/projects/rest_api_demo/venv/lib/python2.7/site-packages/sqlalchemy/engine/base.py", line 1473, in _handle_dbapi_exception
    util.raise_from_cause(sqlalchemy_exception, exc_info)
  File "/home/prahtdooley/projects/rest_api_demo/venv/lib/python2.7/site-packages/sqlalchemy/util/compat.py", line 398, in raise_from_cause
    reraise(type(exception), exception, tb=exc_tb, cause=cause)
  File "/home/prahtdooley/projects/rest_api_demo/venv/lib/python2.7/site-packages/sqlalchemy/engine/base.py", line 1249, in _execute_context
    cursor, statement, parameters, context
  File "/home/prahtdooley/projects/rest_api_demo/venv/lib/python2.7/site-packages/sqlalchemy/engine/default.py", line 580, in do_execute
    cursor.execute(statement, parameters)
IntegrityError: (sqlite3.IntegrityError) PRIMARY KEY must be unique
[SQL: INSERT INTO serverhistory (id, log, timestamp, server_id) VALUES (?, ?, ?, ?)]
[parameters: (1, u'NEW LOG MESSAGE', None, u'0')]
(Background on this error at: http://sqlalche.me/e/gkpj)
{u'timestamp': u'2020-03-06T17:50:18.103Z', u'server_id': u'0', u'log': u'NEW LOG MESSAGE'}
2020-03-06 12:51:37,227 - werkzeug - INFO - 10.32.74.7 - - [06/Mar/2020 12:51:37] "POST /api/build/serverhistories/ HTTP/1.1" 201 -
2020-03-06 12:51:41,671 - werkzeug - INFO - 10.32.74.7 - - [06/Mar/2020 12:51:41] "GET /api/build/servers/?page=1&bool=false&per_page=10 HTTP/1.1" 200 -
2020-03-06 12:51:54,249 - werkzeug - INFO - 10.32.74.7 - - [06/Mar/2020 12:51:54] "GET /api/build/servers/1 HTTP/1.1" 200 -
2020-03-06 12:52:50,897 - werkzeug - INFO - 10.32.74.7 - - [06/Mar/2020 12:52:50] "GET /api/build/servers/1 HTTP/1.1" 200 -
{u'timestamp': u'2020-03-06T17:50:18.103Z', u'server_id': u'1', u'log': u'NEW LOG MESSAGE'}
2020-03-06 12:53:07,904 - werkzeug - INFO - 10.32.74.7 - - [06/Mar/2020 12:53:07] "POST /api/build/serverhistories/ HTTP/1.1" 201 -
{u'timestamp': u'2020-03-06T17:50:18.103Z', u'server_id': u'1', u'log': u'NEW LOG MESSAGE'}
2020-03-06 12:53:09,437 - werkzeug - INFO - 10.32.74.7 - - [06/Mar/2020 12:53:09] "POST /api/build/serverhistories/ HTTP/1.1" 201 -
{u'timestamp': u'2020-03-06T17:50:18.103Z', u'server_id': u'1', u'log': u'NEW LOG MESSAGE'}
2020-03-06 12:53:10,333 - werkzeug - INFO - 10.32.74.7 - - [06/Mar/2020 12:53:10] "POST /api/build/serverhistories/ HTTP/1.1" 201 -
{u'timestamp': u'2020-03-06T17:50:18.103Z', u'server_id': u'1', u'log': u'NEW LOG MESSAGE'}
2020-03-06 12:53:11,224 - werkzeug - INFO - 10.32.74.7 - - [06/Mar/2020 12:53:11] "POST /api/build/serverhistories/ HTTP/1.1" 201 -
2020-03-06 12:53:13,062 - werkzeug - INFO - 10.32.74.7 - - [06/Mar/2020 12:53:13] "GET /api/build/servers/1 HTTP/1.1" 200 -
2020-03-06 12:55:32,755 - werkzeug - INFO - 10.58.143.142 - - [06/Mar/2020 12:55:32] "GET /api/build/servers/?page=1&bool=false&per_page=10 HTTP/1.1" 200 -
2020-03-06 13:30:14,934 - __main__ - INFO - >>>>> Starting development server at http://10.58.143.137:8888/api/ <<<<<
 * Serving Flask app "flaskr" (lazy loading)
 * Environment: production
   WARNING: This is a development server. Do not use it in a production deployment.
   Use a production WSGI server instead.
 * Debug mode: on
2020-03-06 13:30:14,941 - werkzeug - INFO -  * Running on http://10.58.143.137:8888/ (Press CTRL+C to quit)
2020-03-06 13:30:14,944 - werkzeug - INFO -  * Restarting with stat
2020-03-06 13:30:15,474 - __main__ - INFO - >>>>> Starting development server at http://10.58.143.137:8888/api/ <<<<<
2020-03-06 13:30:15,480 - werkzeug - WARNING -  * Debugger is active!
2020-03-06 13:30:15,481 - werkzeug - INFO -  * Debugger PIN: 288-488-263
2020-03-06 13:31:32,556 - __main__ - INFO - >>>>> Starting development server at http://10.58.143.137:8888/api/ <<<<<
 * Serving Flask app "flaskr" (lazy loading)
 * Environment: production
   WARNING: This is a development server. Do not use it in a production deployment.
   Use a production WSGI server instead.
 * Debug mode: on
2020-03-06 13:31:32,562 - werkzeug - INFO -  * Running on http://10.58.143.137:8888/ (Press CTRL+C to quit)
2020-03-06 13:31:32,565 - werkzeug - INFO -  * Restarting with stat
2020-03-06 13:31:33,051 - __main__ - INFO - >>>>> Starting development server at http://10.58.143.137:8888/api/ <<<<<
2020-03-06 13:31:33,057 - werkzeug - WARNING -  * Debugger is active!
2020-03-06 13:31:33,058 - werkzeug - INFO -  * Debugger PIN: 288-488-263
2020-03-06 13:31:35,853 - werkzeug - INFO - 10.32.74.7 - - [06/Mar/2020 13:31:35] "GET /api/ HTTP/1.1" 200 -
2020-03-06 13:31:36,355 - werkzeug - INFO - 10.32.74.7 - - [06/Mar/2020 13:31:36] "GET /api/swagger.json HTTP/1.1" 500 -
2020-03-06 13:31:36,431 - werkzeug - INFO - 10.32.74.7 - - [06/Mar/2020 13:31:36] "GET /swaggerui/favicon-32x32.png HTTP/1.1" 200 -
2020-03-06 13:31:51,445 - werkzeug - INFO - 10.32.74.7 - - [06/Mar/2020 13:31:51] "GET /api/ HTTP/1.1" 200 -
2020-03-06 13:31:51,852 - werkzeug - INFO - 10.32.74.7 - - [06/Mar/2020 13:31:51] "GET /api/swagger.json HTTP/1.1" 500 -
2020-03-06 13:31:51,966 - werkzeug - INFO - 10.32.74.7 - - [06/Mar/2020 13:31:51] "GET /swaggerui/favicon-32x32.png HTTP/1.1" 200 -
2020-03-06 13:32:02,902 - __main__ - INFO - >>>>> Starting development server at http://10.58.143.137:8888/api/ <<<<<
 * Serving Flask app "flaskr" (lazy loading)
 * Environment: production
   WARNING: This is a development server. Do not use it in a production deployment.
   Use a production WSGI server instead.
 * Debug mode: on
2020-03-06 13:32:02,909 - werkzeug - INFO -  * Running on http://10.58.143.137:8888/ (Press CTRL+C to quit)
2020-03-06 13:32:02,911 - werkzeug - INFO -  * Restarting with stat
2020-03-06 13:32:03,405 - __main__ - INFO - >>>>> Starting development server at http://10.58.143.137:8888/api/ <<<<<
2020-03-06 13:32:03,411 - werkzeug - WARNING -  * Debugger is active!
2020-03-06 13:32:03,411 - werkzeug - INFO -  * Debugger PIN: 288-488-263
2020-03-06 13:32:07,440 - werkzeug - INFO - 10.32.74.7 - - [06/Mar/2020 13:32:07] "GET /api/ HTTP/1.1" 200 -
2020-03-06 13:32:07,787 - werkzeug - INFO - 10.32.74.7 - - [06/Mar/2020 13:32:07] "GET /api/swagger.json HTTP/1.1" 500 -
2020-03-06 13:32:07,911 - werkzeug - INFO - 10.32.74.7 - - [06/Mar/2020 13:32:07] "GET /swaggerui/favicon-32x32.png HTTP/1.1" 200 -
2020-03-06 13:33:12,609 - werkzeug - INFO -  * Detected change in '/home/prahtdooley/projects/rest_api_demo/rest_api_demo/api/qc/endpoints/load_servers.py', reloading
2020-03-06 13:33:12,638 - werkzeug - INFO -  * Restarting with stat
2020-03-06 13:33:13,121 - __main__ - INFO - >>>>> Starting development server at http://10.58.143.137:8888/api/ <<<<<
2020-03-06 13:33:13,127 - werkzeug - WARNING -  * Debugger is active!
2020-03-06 13:33:13,128 - werkzeug - INFO -  * Debugger PIN: 288-488-263
2020-03-06 13:33:30,425 - werkzeug - INFO -  * Detected change in '/home/prahtdooley/projects/rest_api_demo/rest_api_demo/api/qc/endpoints/load_servers.py', reloading
2020-03-06 13:33:30,455 - werkzeug - INFO -  * Restarting with stat
2020-03-06 13:33:30,952 - __main__ - INFO - >>>>> Starting development server at http://10.58.143.137:8888/api/ <<<<<
2020-03-06 13:33:30,958 - werkzeug - WARNING -  * Debugger is active!
2020-03-06 13:33:30,959 - werkzeug - INFO -  * Debugger PIN: 288-488-263
2020-03-06 13:33:33,704 - werkzeug - INFO - 10.32.74.7 - - [06/Mar/2020 13:33:33] "GET /api/ HTTP/1.1" 200 -
2020-03-06 13:33:33,983 - werkzeug - INFO - 10.32.74.7 - - [06/Mar/2020 13:33:33] "GET /api/swagger.json HTTP/1.1" 200 -
2020-03-06 13:33:34,062 - werkzeug - INFO - 10.32.74.7 - - [06/Mar/2020 13:33:34] "GET /swaggerui/favicon-32x32.png HTTP/1.1" 200 -
2020-03-06 13:36:53,487 - werkzeug - INFO -  * Detected change in '/home/prahtdooley/projects/rest_api_demo/rest_api_demo/api/qc/endpoints/get_minion_id.py', reloading
2020-03-06 13:36:53,518 - werkzeug - INFO -  * Restarting with stat
2020-03-06 13:36:54,001 - __main__ - INFO - >>>>> Starting development server at http://10.58.143.137:8888/api/ <<<<<
2020-03-06 13:36:54,008 - werkzeug - WARNING -  * Debugger is active!
2020-03-06 13:36:54,009 - werkzeug - INFO -  * Debugger PIN: 288-488-263
2020-03-06 13:38:50,944 - werkzeug - INFO -  * Detected change in '/home/prahtdooley/projects/rest_api_demo/rest_api_demo/api/qc/endpoints/load_servers.py', reloading
2020-03-06 13:38:50,977 - werkzeug - INFO -  * Restarting with stat
2020-03-06 13:38:51,470 - __main__ - INFO - >>>>> Starting development server at http://10.58.143.137:8888/api/ <<<<<
2020-03-06 13:38:51,476 - werkzeug - WARNING -  * Debugger is active!
2020-03-06 13:38:51,477 - werkzeug - INFO -  * Debugger PIN: 288-488-263
2020-03-06 13:38:55,310 - werkzeug - INFO - 10.32.74.7 - - [06/Mar/2020 13:38:55] "GET /api/ HTTP/1.1" 200 -
2020-03-06 13:38:55,751 - werkzeug - INFO - 10.32.74.7 - - [06/Mar/2020 13:38:55] "GET /api/swagger.json HTTP/1.1" 500 -
2020-03-06 13:38:55,832 - werkzeug - INFO - 10.32.74.7 - - [06/Mar/2020 13:38:55] "GET /swaggerui/favicon-32x32.png HTTP/1.1" 200 -
2020-03-06 13:42:44,482 - werkzeug - INFO -  * Detected change in '/home/prahtdooley/projects/rest_api_demo/rest_api_demo/api/qc/endpoints/load_servers.py', reloading
2020-03-06 13:42:44,517 - werkzeug - INFO -  * Restarting with stat
2020-03-06 13:42:45,003 - __main__ - INFO - >>>>> Starting development server at http://10.58.143.137:8888/api/ <<<<<
2020-03-06 13:42:45,009 - werkzeug - WARNING -  * Debugger is active!
2020-03-06 13:42:45,009 - werkzeug - INFO -  * Debugger PIN: 288-488-263
2020-03-06 13:42:59,263 - werkzeug - INFO -  * Detected change in '/home/prahtdooley/projects/rest_api_demo/rest_api_demo/api/qc/endpoints/load_servers.py', reloading
2020-03-06 13:42:59,301 - werkzeug - INFO -  * Restarting with stat
2020-03-06 13:42:59,802 - __main__ - INFO - >>>>> Starting development server at http://10.58.143.137:8888/api/ <<<<<
2020-03-06 13:42:59,808 - werkzeug - WARNING -  * Debugger is active!
2020-03-06 13:42:59,808 - werkzeug - INFO -  * Debugger PIN: 288-488-263
2020-03-06 13:43:02,391 - werkzeug - INFO - 10.32.74.7 - - [06/Mar/2020 13:43:02] "GET /api/ HTTP/1.1" 200 -
2020-03-06 13:43:02,798 - werkzeug - INFO - 10.32.74.7 - - [06/Mar/2020 13:43:02] "GET /api/swagger.json HTTP/1.1" 200 -
2020-03-06 13:43:02,871 - werkzeug - INFO - 10.32.74.7 - - [06/Mar/2020 13:43:02] "GET /swaggerui/favicon-32x32.png HTTP/1.1" 200 -
2020-03-06 13:43:49,687 - werkzeug - INFO -  * Detected change in '/home/prahtdooley/projects/rest_api_demo/rest_api_demo/api/qc/endpoints/load_servers.py', reloading
2020-03-06 13:43:49,719 - werkzeug - INFO -  * Restarting with stat
2020-03-06 13:43:50,215 - __main__ - INFO - >>>>> Starting development server at http://10.58.143.137:8888/api/ <<<<<
2020-03-06 13:43:50,222 - werkzeug - WARNING -  * Debugger is active!
2020-03-06 13:43:50,222 - werkzeug - INFO -  * Debugger PIN: 288-488-263
2020-03-06 13:43:52,717 - werkzeug - INFO - 10.32.74.7 - - [06/Mar/2020 13:43:52] "GET /api/ HTTP/1.1" 200 -
2020-03-06 13:43:53,035 - werkzeug - INFO - 10.32.74.7 - - [06/Mar/2020 13:43:53] "GET /api/swagger.json HTTP/1.1" 200 -
2020-03-06 13:43:53,107 - werkzeug - INFO - 10.32.74.7 - - [06/Mar/2020 13:43:53] "GET /swaggerui/favicon-32x32.png HTTP/1.1" 200 -
2020-03-06 13:44:15,188 - __main__ - INFO - >>>>> Starting development server at http://10.58.143.137:8888/api/ <<<<<
 * Serving Flask app "flaskr" (lazy loading)
 * Environment: production
   WARNING: This is a development server. Do not use it in a production deployment.
   Use a production WSGI server instead.
 * Debug mode: on
2020-03-06 13:44:15,196 - werkzeug - INFO -  * Running on http://10.58.143.137:8888/ (Press CTRL+C to quit)
2020-03-06 13:44:15,198 - werkzeug - INFO -  * Restarting with stat
2020-03-06 13:44:15,692 - __main__ - INFO - >>>>> Starting development server at http://10.58.143.137:8888/api/ <<<<<
2020-03-06 13:44:15,698 - werkzeug - WARNING -  * Debugger is active!
2020-03-06 13:44:15,698 - werkzeug - INFO -  * Debugger PIN: 288-488-263
2020-03-06 13:44:17,520 - werkzeug - INFO - 10.32.74.7 - - [06/Mar/2020 13:44:17] "GET /api/ HTTP/1.1" 200 -
2020-03-06 13:44:17,816 - werkzeug - INFO - 10.32.74.7 - - [06/Mar/2020 13:44:17] "GET /api/swagger.json HTTP/1.1" 200 -
2020-03-06 13:44:17,885 - werkzeug - INFO - 10.32.74.7 - - [06/Mar/2020 13:44:17] "GET /swaggerui/favicon-32x32.png HTTP/1.1" 200 -
2020-03-06 13:45:50,695 - werkzeug - INFO - 10.32.74.7 - - [06/Mar/2020 13:45:50] "POST /api/qc/load_servers/ HTTP/1.1" 200 -
2020-03-06 13:46:17,839 - werkzeug - INFO - 10.32.74.7 - - [06/Mar/2020 13:46:17] "POST /api/qc/load_servers/ HTTP/1.1" 200 -
2020-03-06 13:46:44,252 - werkzeug - INFO -  * Detected change in '/home/prahtdooley/projects/rest_api_demo/rest_api_demo/api/qc/endpoints/load_servers.py', reloading
2020-03-06 13:46:44,281 - werkzeug - INFO -  * Restarting with stat
2020-03-06 13:46:44,768 - __main__ - INFO - >>>>> Starting development server at http://10.58.143.137:8888/api/ <<<<<
2020-03-06 13:46:44,774 - werkzeug - WARNING -  * Debugger is active!
2020-03-06 13:46:44,775 - werkzeug - INFO -  * Debugger PIN: 288-488-263
2020-03-06 13:46:48,686 - werkzeug - INFO - 10.32.74.7 - - [06/Mar/2020 13:46:48] "POST /api/qc/load_servers/ HTTP/1.1" 200 -
2020-03-06 13:47:14,292 - werkzeug - INFO -  * Detected change in '/home/prahtdooley/projects/rest_api_demo/rest_api_demo/flaskr.py', reloading
2020-03-06 13:47:14,323 - werkzeug - INFO -  * Restarting with stat
2020-03-06 13:47:14,820 - __main__ - INFO - >>>>> Starting development server at http://10.58.143.137:8888/api/ <<<<<
2020-03-06 13:47:14,826 - werkzeug - WARNING -  * Debugger is active!
2020-03-06 13:47:14,827 - werkzeug - INFO -  * Debugger PIN: 288-488-263
2020-03-06 14:02:06,000 - werkzeug - INFO -  * Detected change in '/home/prahtdooley/projects/rest_api_demo/rest_api_demo/api/qc/endpoints/load_servers.py', reloading
2020-03-06 14:02:06,039 - werkzeug - INFO -  * Restarting with stat
Traceback (most recent call last):
  File "/home/prahtdooley/projects/rest_api_demo/rest_api_demo/flaskr.py", line 12, in <module>
    from rest_api_demo.api.qc.endpoints.load_servers import ns as load_servers
  File "/home/prahtdooley/projects/rest_api_demo/rest_api_demo/api/qc/endpoints/load_servers.py", line 26
    return data[0]
         ^
IndentationError: expected an indented block
Traceback (most recent call last):
  File "rest_api_demo/flaskr.py", line 12, in <module>
    from rest_api_demo.api.qc.endpoints.load_servers import ns as load_servers
  File "/home/prahtdooley/projects/rest_api_demo/rest_api_demo/api/qc/endpoints/load_servers.py", line 18, in <module>
    class Parse(Resource):
  File "/home/prahtdooley/projects/rest_api_demo/rest_api_demo/api/qc/endpoints/load_servers.py", line 19, in Parse
    @api.expect(page_of_servers)
NameError: name 'page_of_servers' is not defined
2020-03-06 14:02:50,827 - __main__ - INFO - >>>>> Starting development server at http://10.58.143.137:8888/api/ <<<<<
 * Serving Flask app "flaskr" (lazy loading)
 * Environment: production
   WARNING: This is a development server. Do not use it in a production deployment.
   Use a production WSGI server instead.
 * Debug mode: on
2020-03-06 14:02:50,834 - werkzeug - INFO -  * Running on http://10.58.143.137:8888/ (Press CTRL+C to quit)
2020-03-06 14:02:50,837 - werkzeug - INFO -  * Restarting with stat
2020-03-06 14:02:51,333 - __main__ - INFO - >>>>> Starting development server at http://10.58.143.137:8888/api/ <<<<<
2020-03-06 14:02:51,339 - werkzeug - WARNING -  * Debugger is active!
2020-03-06 14:02:51,340 - werkzeug - INFO -  * Debugger PIN: 288-488-263
2020-03-06 14:02:56,494 - werkzeug - INFO - 10.32.74.7 - - [06/Mar/2020 14:02:56] "GET /api/ HTTP/1.1" 200 -
2020-03-06 14:02:56,897 - werkzeug - INFO - 10.32.74.7 - - [06/Mar/2020 14:02:56] "GET /api/swagger.json HTTP/1.1" 200 -
2020-03-06 14:02:56,976 - werkzeug - INFO - 10.32.74.7 - - [06/Mar/2020 14:02:56] "GET /swaggerui/favicon-32x32.png HTTP/1.1" 200 -
2020-03-06 14:03:21,181 - werkzeug - INFO - 10.32.74.7 - - [06/Mar/2020 14:03:21] "POST /api/qc/load_servers/ HTTP/1.1" 500 -
Traceback (most recent call last):
  File "/home/prahtdooley/projects/rest_api_demo/venv/lib/python2.7/site-packages/flask/app.py", line 2463, in __call__
    return self.wsgi_app(environ, start_response)
  File "/home/prahtdooley/projects/rest_api_demo/venv/lib/python2.7/site-packages/flask/app.py", line 2449, in wsgi_app
    response = self.handle_exception(e)
  File "/home/prahtdooley/projects/rest_api_demo/venv/lib/python2.7/site-packages/flask_restx/api.py", line 599, in error_router
    return original_handler(f)
  File "/home/prahtdooley/projects/rest_api_demo/venv/lib/python2.7/site-packages/flask/app.py", line 1866, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "/home/prahtdooley/projects/rest_api_demo/venv/lib/python2.7/site-packages/flask_restx/api.py", line 597, in error_router
    return self.handle_error(e)
  File "/home/prahtdooley/projects/rest_api_demo/venv/lib/python2.7/site-packages/flask/app.py", line 2446, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/prahtdooley/projects/rest_api_demo/venv/lib/python2.7/site-packages/flask/app.py", line 1951, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/prahtdooley/projects/rest_api_demo/venv/lib/python2.7/site-packages/flask_restx/api.py", line 599, in error_router
    return original_handler(f)
  File "/home/prahtdooley/projects/rest_api_demo/venv/lib/python2.7/site-packages/flask/app.py", line 1820, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/home/prahtdooley/projects/rest_api_demo/venv/lib/python2.7/site-packages/flask_restx/api.py", line 597, in error_router
    return self.handle_error(e)
  File "/home/prahtdooley/projects/rest_api_demo/venv/lib/python2.7/site-packages/flask/app.py", line 1949, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/prahtdooley/projects/rest_api_demo/venv/lib/python2.7/site-packages/flask/app.py", line 1935, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/home/prahtdooley/projects/rest_api_demo/venv/lib/python2.7/site-packages/flask_restx/api.py", line 339, in wrapper
    resp = resource(*args, **kwargs)
  File "/home/prahtdooley/projects/rest_api_demo/venv/lib/python2.7/site-packages/flask/views.py", line 89, in view
    return self.dispatch_request(*args, **kwargs)
  File "/home/prahtdooley/projects/rest_api_demo/venv/lib/python2.7/site-packages/flask_restx/resource.py", line 44, in dispatch_request
    resp = meth(*args, **kwargs)
  File "/home/prahtdooley/projects/rest_api_demo/rest_api_demo/api/qc/endpoints/load_servers.py", line 25, in post
    return servers[0]
KeyError: 0
2020-03-06 14:03:44,266 - werkzeug - INFO -  * Detected change in '/home/prahtdooley/projects/rest_api_demo/rest_api_demo/api/qc/endpoints/load_servers.py', reloading
2020-03-06 14:03:44,299 - werkzeug - INFO -  * Restarting with stat
2020-03-06 14:03:44,789 - __main__ - INFO - >>>>> Starting development server at http://10.58.143.137:8888/api/ <<<<<
2020-03-06 14:03:44,795 - werkzeug - WARNING -  * Debugger is active!
2020-03-06 14:03:44,796 - werkzeug - INFO -  * Debugger PIN: 288-488-263
2020-03-06 14:03:47,019 - werkzeug - INFO - 10.32.74.7 - - [06/Mar/2020 14:03:47] "POST /api/qc/load_servers/ HTTP/1.1" 200 -
2020-03-06 14:04:33,636 - werkzeug - INFO -  * Detected change in '/home/prahtdooley/projects/rest_api_demo/rest_api_demo/api/qc/endpoints/load_servers.py', reloading
2020-03-06 14:04:33,668 - werkzeug - INFO -  * Restarting with stat
2020-03-06 14:04:34,168 - __main__ - INFO - >>>>> Starting development server at http://10.58.143.137:8888/api/ <<<<<
2020-03-06 14:04:34,174 - werkzeug - WARNING -  * Debugger is active!
2020-03-06 14:04:34,174 - werkzeug - INFO -  * Debugger PIN: 288-488-263
2020-03-06 14:04:48,787 - __main__ - INFO - >>>>> Starting development server at http://10.58.143.137:8888/api/ <<<<<
 * Serving Flask app "flaskr" (lazy loading)
 * Environment: production
   WARNING: This is a development server. Do not use it in a production deployment.
   Use a production WSGI server instead.
 * Debug mode: on
2020-03-06 14:04:48,795 - werkzeug - INFO -  * Running on http://10.58.143.137:8888/ (Press CTRL+C to quit)
2020-03-06 14:04:48,798 - werkzeug - INFO -  * Restarting with stat
2020-03-06 14:04:49,313 - __main__ - INFO - >>>>> Starting development server at http://10.58.143.137:8888/api/ <<<<<
2020-03-06 14:04:49,320 - werkzeug - WARNING -  * Debugger is active!
2020-03-06 14:04:49,321 - werkzeug - INFO -  * Debugger PIN: 288-488-263
2020-03-06 14:04:52,033 - werkzeug - INFO - 10.32.74.7 - - [06/Mar/2020 14:04:52] "GET /api/ HTTP/1.1" 200 -
2020-03-06 14:04:52,474 - werkzeug - INFO - 10.32.74.7 - - [06/Mar/2020 14:04:52] "GET /api/swagger.json HTTP/1.1" 200 -
2020-03-06 14:04:52,545 - werkzeug - INFO - 10.32.74.7 - - [06/Mar/2020 14:04:52] "GET /swaggerui/favicon-32x32.png HTTP/1.1" 200 -
2020-03-06 14:05:32,932 - werkzeug - INFO - 10.32.74.7 - - [06/Mar/2020 14:05:32] "POST /api/qc/load_servers/ HTTP/1.1" 500 -
Traceback (most recent call last):
  File "/home/prahtdooley/projects/rest_api_demo/venv/lib/python2.7/site-packages/flask/app.py", line 2463, in __call__
    return self.wsgi_app(environ, start_response)
  File "/home/prahtdooley/projects/rest_api_demo/venv/lib/python2.7/site-packages/flask/app.py", line 2449, in wsgi_app
    response = self.handle_exception(e)
  File "/home/prahtdooley/projects/rest_api_demo/venv/lib/python2.7/site-packages/flask_restx/api.py", line 599, in error_router
    return original_handler(f)
  File "/home/prahtdooley/projects/rest_api_demo/venv/lib/python2.7/site-packages/flask/app.py", line 1866, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "/home/prahtdooley/projects/rest_api_demo/venv/lib/python2.7/site-packages/flask_restx/api.py", line 597, in error_router
    return self.handle_error(e)
  File "/home/prahtdooley/projects/rest_api_demo/venv/lib/python2.7/site-packages/flask/app.py", line 2446, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/prahtdooley/projects/rest_api_demo/venv/lib/python2.7/site-packages/flask/app.py", line 1951, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/prahtdooley/projects/rest_api_demo/venv/lib/python2.7/site-packages/flask_restx/api.py", line 599, in error_router
    return original_handler(f)
  File "/home/prahtdooley/projects/rest_api_demo/venv/lib/python2.7/site-packages/flask/app.py", line 1820, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/home/prahtdooley/projects/rest_api_demo/venv/lib/python2.7/site-packages/flask_restx/api.py", line 597, in error_router
    return self.handle_error(e)
  File "/home/prahtdooley/projects/rest_api_demo/venv/lib/python2.7/site-packages/flask/app.py", line 1949, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/prahtdooley/projects/rest_api_demo/venv/lib/python2.7/site-packages/flask/app.py", line 1935, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/home/prahtdooley/projects/rest_api_demo/venv/lib/python2.7/site-packages/flask_restx/api.py", line 339, in wrapper
    resp = resource(*args, **kwargs)
  File "/home/prahtdooley/projects/rest_api_demo/venv/lib/python2.7/site-packages/flask/views.py", line 89, in view
    return self.dispatch_request(*args, **kwargs)
  File "/home/prahtdooley/projects/rest_api_demo/venv/lib/python2.7/site-packages/flask_restx/resource.py", line 44, in dispatch_request
    resp = meth(*args, **kwargs)
  File "/home/prahtdooley/projects/rest_api_demo/rest_api_demo/api/qc/endpoints/load_servers.py", line 24, in post
    create_server(server)
NameError: global name 'create_server' is not defined
2020-03-06 14:05:58,561 - werkzeug - INFO -  * Detected change in '/home/prahtdooley/projects/rest_api_demo/rest_api_demo/api/qc/endpoints/load_servers.py', reloading
2020-03-06 14:05:58,593 - werkzeug - INFO -  * Restarting with stat
2020-03-06 14:05:59,081 - __main__ - INFO - >>>>> Starting development server at http://10.58.143.137:8888/api/ <<<<<
2020-03-06 14:05:59,087 - werkzeug - WARNING -  * Debugger is active!
2020-03-06 14:05:59,087 - werkzeug - INFO -  * Debugger PIN: 288-488-263
2020-03-06 14:06:01,505 - werkzeug - INFO - 10.32.74.7 - - [06/Mar/2020 14:06:01] "POST /api/qc/load_servers/ HTTP/1.1" 500 -
Traceback (most recent call last):
  File "/home/prahtdooley/projects/rest_api_demo/venv/lib/python2.7/site-packages/flask/app.py", line 2463, in __call__
    return self.wsgi_app(environ, start_response)
  File "/home/prahtdooley/projects/rest_api_demo/venv/lib/python2.7/site-packages/flask/app.py", line 2449, in wsgi_app
    response = self.handle_exception(e)
  File "/home/prahtdooley/projects/rest_api_demo/venv/lib/python2.7/site-packages/flask_restx/api.py", line 599, in error_router
    return original_handler(f)
  File "/home/prahtdooley/projects/rest_api_demo/venv/lib/python2.7/site-packages/flask/app.py", line 1866, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "/home/prahtdooley/projects/rest_api_demo/venv/lib/python2.7/site-packages/flask_restx/api.py", line 597, in error_router
    return self.handle_error(e)
  File "/home/prahtdooley/projects/rest_api_demo/venv/lib/python2.7/site-packages/flask/app.py", line 2446, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/prahtdooley/projects/rest_api_demo/venv/lib/python2.7/site-packages/flask/app.py", line 1951, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/prahtdooley/projects/rest_api_demo/venv/lib/python2.7/site-packages/flask_restx/api.py", line 599, in error_router
    return original_handler(f)
  File "/home/prahtdooley/projects/rest_api_demo/venv/lib/python2.7/site-packages/flask/app.py", line 1820, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/home/prahtdooley/projects/rest_api_demo/venv/lib/python2.7/site-packages/flask_restx/api.py", line 597, in error_router
    return self.handle_error(e)
  File "/home/prahtdooley/projects/rest_api_demo/venv/lib/python2.7/site-packages/flask/app.py", line 1949, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/prahtdooley/projects/rest_api_demo/venv/lib/python2.7/site-packages/flask/app.py", line 1935, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/home/prahtdooley/projects/rest_api_demo/venv/lib/python2.7/site-packages/flask_restx/api.py", line 339, in wrapper
    resp = resource(*args, **kwargs)
  File "/home/prahtdooley/projects/rest_api_demo/venv/lib/python2.7/site-packages/flask/views.py", line 89, in view
    return self.dispatch_request(*args, **kwargs)
  File "/home/prahtdooley/projects/rest_api_demo/venv/lib/python2.7/site-packages/flask_restx/resource.py", line 44, in dispatch_request
    resp = meth(*args, **kwargs)
  File "/home/prahtdooley/projects/rest_api_demo/rest_api_demo/api/qc/endpoints/load_servers.py", line 25, in post
    create_server(server)
  File "/home/prahtdooley/projects/rest_api_demo/rest_api_demo/api/build/business.py", line 12, in create_server
    minion_id = data.get('minion_id')
AttributeError: 'unicode' object has no attribute 'get'
2020-03-06 14:06:36,744 - werkzeug - INFO -  * Detected change in '/home/prahtdooley/projects/rest_api_demo/rest_api_demo/api/qc/endpoints/load_servers.py', reloading
2020-03-06 14:06:36,777 - werkzeug - INFO -  * Restarting with stat
2020-03-06 14:06:37,275 - __main__ - INFO - >>>>> Starting development server at http://10.58.143.137:8888/api/ <<<<<
2020-03-06 14:06:37,282 - werkzeug - WARNING -  * Debugger is active!
2020-03-06 14:06:37,283 - werkzeug - INFO -  * Debugger PIN: 288-488-263
2020-03-06 14:06:39,925 - werkzeug - INFO - 10.32.74.7 - - [06/Mar/2020 14:06:39] "POST /api/qc/load_servers/ HTTP/1.1" 201 -
2020-03-06 14:06:48,421 - werkzeug - INFO - 10.32.74.7 - - [06/Mar/2020 14:06:48] "GET /api/build/servers/?page=1&bool=true&per_page=10 HTTP/1.1" 200 -
